export enum FinancialInputRangesEnum {
  BUDGET = "budget",
  INITIAL_INVESTMENT = "initialInvestment",
  ANNUAL_OPERATING_COSTS = "annualOperatingCosts",
  ANNUAL_OPERATING_COSTS_GROWTH_RATE = "annualOperatingCostsGrowthRate",
  FIRST_ANNUAL_OPERATING_COST_YEAR = "firstAnnualOperatingCostYear",
  ANNUAL_MAINTENANCE_COSTS = "annualMaintenanceCosts",
  ANNUAL_MAINTENANCE_COSTS_GROWTH_RATE = "annualMaintenanceCostsGrowthRate",
  FIRST_ANNUAL_MAINTENANCE_COST_YEAR = "firstAnnualMaintenanceCostYear",
  TRAINING_COSTS = "trainingCosts",
  ANNUAL_REVENUE = "annualRevenue",
  ANNUAL_REVENUE_GROWTH_RATE = "annualRevenueGrowthRate",
  FIRST_REVENUE_GENERATING_YEAR = "firstRevenueGeneratingYear",
  ANNUAL_COST_SAVINGS = "annualCostSavings",
  ANNUAL_COST_SAVINGS_GROWTH_RATE = "annualCostSavingsGrowthRate",
  FIRST_COST_SAVING_YEAR = "firstCostSavingYear",
  PROJECT_DURATION = "projectDuration",
  RISK_FACTOR = "riskFactor",
  DISCOUNT_RATE = "discountRate",
  DYNAMIC_INPUT = "dynamicFinancialInputs",
}
